# Generated by Django 5.0.3 on 2024-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AusPostcode',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('postcode', models.CharField(default=None, max_length=5)),
                ('suburb', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=4)),
                ('latitude', models.FloatField(default=None, max_length=9)),
                ('longitude', models.FloatField(default=None, max_length=9)),
            ],
        ),
    ]
