# Generated by Django 5.0.3 on 2024-04-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breathe_Ease_Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('loc_postcode', models.CharField(default=None, max_length=5)),
                ('loc_suburb', models.CharField(default=None, max_length=100)),
                ('loc_state', models.CharField(default=None, max_length=4)),
                ('loc_latitude', models.FloatField(default=None, max_length=9)),
                ('loc_longitude', models.FloatField(default=None, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pyegrass',
            fields=[
                ('pye_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pye_lat', models.FloatField(default=None, max_length=9)),
                ('pye_lon', models.FloatField(default=None, max_length=9)),
                ('pye_datetime', models.DateTimeField(default=None, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='AusPostcode',
        ),
    ]
