# Generated by Django 5.0.3 on 2024-04-02 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Breathe_Ease_Home', '0002_location_pyegrass_delete_auspostcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc_latitude',
            new_name='loc_lat',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_longitude',
            new_name='loc_long',
        ),
    ]
