# Generated by Django 5.0.3 on 2024-04-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Breathe_Ease_Home', '0004_pyegrass_pye_country_pyegrass_pye_country_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pyegrass',
            new_name='Ryegrass',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_country',
            new_name='rye_country',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_country_code',
            new_name='rye_country_code',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_datetime',
            new_name='rye_datetime',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_day',
            new_name='rye_day',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_id',
            new_name='rye_id',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_lat',
            new_name='rye_lat',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_lon',
            new_name='rye_lon',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_month',
            new_name='rye_month',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_record_by',
            new_name='rye_record_by',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_scientific_name',
            new_name='rye_scientific_name',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_vernacular_name',
            new_name='rye_vernacular_name',
        ),
        migrations.RenameField(
            model_name='ryegrass',
            old_name='pye_year',
            new_name='rye_year',
        ),
    ]
