# Generated by Django 5.0.3 on 2024-04-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Breathe_Ease_Home', '0005_rename_pyegrass_ryegrass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ryegrass',
            name='rye_country',
        ),
        migrations.RemoveField(
            model_name='ryegrass',
            name='rye_country_code',
        ),
        migrations.RemoveField(
            model_name='ryegrass',
            name='rye_datetime',
        ),
        migrations.RemoveField(
            model_name='ryegrass',
            name='rye_day',
        ),
        migrations.RemoveField(
            model_name='ryegrass',
            name='rye_month',
        ),
        migrations.RemoveField(
            model_name='ryegrass',
            name='rye_year',
        ),
        migrations.AddField(
            model_name='ryegrass',
            name='rye_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ryegrass',
            name='rye_taxon_concept_id',
            field=models.URLField(default=None, null=True),
        ),
    ]
