# Generated by Django 5.0.3 on 2024-04-03 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Breathe_Ease', '0003_rename_loc_latitude_location_loc_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyegrass',
            name='pye_country',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pyegrass',
            name='pye_country_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pyegrass',
            name='pye_day',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1),
                                                                           django.core.validators.MaxValueValidator(
                                                                               31)]),
        ),
        migrations.AddField(
            model_name='pyegrass',
            name='pye_month',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1),
                                                                           django.core.validators.MaxValueValidator(
                                                                               12)]),
        ),
        migrations.AddField(
            model_name='pyegrass',
            name='pye_record_by',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pyegrass',
            name='pye_scientific_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pyegrass',
            name='pye_vernacular_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pyegrass',
            name='pye_year',
            field=models.IntegerField(default=None, null=True,
                                      validators=[django.core.validators.MinValueValidator(1000),
                                                  django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='pyegrass',
            name='pye_datetime',
            field=models.DateTimeField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pyegrass',
            name='pye_lat',
            field=models.FloatField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='pyegrass',
            name='pye_lon',
            field=models.FloatField(default=None, max_length=10),
        ),
    ]
