# Generated by Django 5.0.3 on 2024-04-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Breathe_Ease', '0006_remove_ryegrass_rye_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ryegrass',
            name='rye_lat',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='ryegrass',
            name='rye_lon',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
